version: '3'
services:
  web:
    container_name: web
    image: yjjjwww/cicd-web
    expose:
      - 8080
    ports:
      - 8080:8080
  nginx:
    container_name: nginx
    image: yjjjwww/cicd-nginx
    ports:
      - 80:80
    depends_on:
      - web