name: github-actions
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Branch
        run: echo "Current branch is ${GITHUB_REF#refs/heads/}"

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --platform amd64 --build-arg DEPENDENCY=build/dependency -t ${{ secrets.DOCKER_REPO }}/cicd-web .
          docker push ${{ secrets.DOCKER_REPO }}/cicd-web

      - name: Copy Docker Compose file to EC2 instance
        run: |
          echo "$KEY" > key.pem
          chmod 400 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml ubuntu@${{ secrets.HOST }}:/home/ubuntu/
          rm key.pem

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo chmod 666 /var/run/docker.sock
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/cicd-web
            sudo docker compose up -d
            sudo docker image prune -f